# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240fc213858fb0f4a909dcacae4ec7ae899efa9999647a3d11fa04a677e487421d332cd977abcc0fdce15c5675f94ddf93ab2b8803a73b6a9a9d3fb19bebd0df

test:
  secret_key_base: c6da96af005b9fbb3e2579059f7192931d2a154c08b4b8f5269f02c866202738e1b5014b6710385e2c2ba25524df1416af05e4b8b30feac5a5242e375129e77d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
