# User seeds
users = User.create([{ name: "Snoopy", email: "snoopy@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now},
										 { name: "Charlie Brown", email: "charlie@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now},
										 { name: "Linus van Pelt", email: "linus@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Woodstock", email: "woodstock@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Lucy van Pelt", email: "lucy@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Schroeder", email: "schroeder@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Sally Brown", email: "sally@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Pig-Pen", email: "pigpen@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Peppermint Patty", email: "patty@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now },
										 { name: "Violet Gray", email: "violet@peanuts.com", 
											 password: "peanuts", confirmed_at: Time.now }])

# Post seeds
posts = Post.create([{ content: "The joy is in the playing.", user_id: 6 },
										 { content: "I got a rock.", user_id: 2 },
										 { content: "Happiness is a warm puppy", user_id: 5 },
										 { content: "It was a dark and stormy night...", 
										 	 user_id: 1 },
										 { content: "I was a victim of false doctrine.", 
										 	 user_id: 3 },
										 { content: "Stop calling me sir!", user_id: 9 },
										 { content: "That's the way it goes...", user_id: 2 },
										 { content: "Kiss her, you blockhead!", user_id: 7 },
										 { content: "There are three things I have learned never "\
										 	          "to discuss with people...religion, politics" \
										 	          "and the Great Pumpkin!", user_id: 3 }])

friendships = Friendship.create([{ friended_id: 1, friender_id: 3, 
																	 accepted: true },
																 { friended_id: 1, friender_id: 2, 
																	 accepted: true },
																 { friended_id: 2, friender_id: 3, 
																	 accepted: true },
																 { friended_id: 4, friender_id: 6, 
																	 accepted: true },
																 { friended_id: 5, friender_id: 10, 
																	 accepted: true },
																 { friended_id: 9, friender_id: 8, 
																	 accepted: true },
																 { friended_id: 7, friender_id: 3, 
																	 accepted: true },
																 { friended_id: 10, friender_id: 3, 
																	 accepted: true },
																 { friended_id: 6, friender_id: 1, 
																	 accepted: true },
																 { friended_id: 6, friender_id: 9, 
																	 accepted: false },
																 { friended_id: 1, friender_id: 10, 
																	 accepted: false },
																 { friended_id: 2, friender_id: 4, 
																	 accepted: false },
																 { friended_id: 3, friender_id: 4, 
																	 accepted: false },
																 { friended_id: 4, friender_id: 10, 
																	 accepted: false },
																 { friended_id: 5, friender_id: 1, 
																	 accepted: false },
																 { friended_id: 6, friender_id: 2, 
																	 accepted: false },
																 { friended_id: 7, friender_id: 9, 
																	 accepted: false },
																 { friended_id: 8, friender_id: 1, 
																	 accepted: false },
																 { friended_id: 9, friender_id: 1, 
																	 accepted: false },
																 { friended_id: 10, friender_id: 2, 
																	 accepted: false }])
