# User seeds
users = User.create([{ name: "Snoopy", email: "snoopy@peanuts.com", 
											 password: "peanuts" },
										 { name: "Charlie Brown", email: "charlie@peanuts.com", 
											 password: "peanuts" },
										 { name: "Linus van Pelt", email: "linus@peanuts.com", 
											 password: "peanuts" },
										 { name: "Woodstock", email: "woodstock@peanuts.com", 
											 password: "peanuts" },
										 { name: "Lucy van Pelt", email: "lucy@peanuts.com", 
											 password: "peanuts" },
										 { name: "Schroeder", email: "schroeder@peanuts.com", 
											 password: "peanuts" },
										 { name: "Sally Brown", email: "sally@peanuts.com", 
											 password: "peanuts" },
										 { name: "Pig-Pen", email: "pigpen@peanuts.com", 
											 password: "peanuts" },
										 { name: "Peppermint Patty", email: "patty@peanuts.com", 
											 password: "peanuts" },
										 { name: "Violet Gray", email: "violet@peanuts.com", 
											 password: "peanuts" },
											 ])
